spring:
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: fabric
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    database: postgresql
server:
  servlet:
    context-path: /api
  port: 8090
---
spring:
  profiles: development
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
---
spring:
  profiles: production
logging:
  level:
    root: ERROR